version: "3"

services:

  node:
    build: .
    user: node
    container_name: blogs_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      API_PORT: 3001
      NODE_ENV: 'development'
    networks:
      - blogs_api_net
  db:
    container_name: blogs_api_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u",
          "root",
          "-ppassword"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - blogs_api_net
networks:
  blogs_api_net:
    driver: bridge
